# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CSI',
                'doc_host': 'https://ukc10014.github.io',
                'git_url': 'https://github.com/ukc10014/CSI',
                'lib_path': 'CSI'},
  'syms': {'CSI.core': {'CSI.core.foo': ('core.html#foo', 'CSI/core.py')}}}
